---
- name: Stop the entire TIBCO ESB Sute (by Hari Iyer).
  hosts: Tibco-<landscape>
  user: tibuser
  sudo: no

  tasks:
    - name: Stop TIBCO QA
      shell: >
        kill -SIGTERM `ps -eaf|grep -i bwengine|grep -v grep|awk '{print $2}'`
        sleep 60
        kill -SIGKILL `ps -eaf|grep -i hawk|grep -v grep|awk  '{print $2}'`
        sleep 60
        kill -SIGKILL `ps -eaf|grep -i tibcoadmin|grep -v grep|awk  '{print $2}'`
        sleep 60
        kill -SIGTERM `ps -eaf|grep -i adr3|grep -v grep|awk  '{print $2}'`
        kill -SIGTERM `ps -eaf|grep -i adadb|grep -v grep|awk  '{print $2}'`
        kill -SIGTERM `ps -eaf|grep -i adldap|grep -v grep|awk  '{print $2}'`
        sleep 60
        kill -SIGTERM `ps -eaf|grep -i ems|grep -v grep|awk  '{print $2}'`